name: Deploy Template

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      ssh_password:
        required: true
      slack_webhook_url:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - name: Set Image Tag
        id: set_tag
        run: echo "tag=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build Docker Image (remote)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: marcusabukari.nl
          username: marcusabukari
          password: ${{ secrets.ssh_password }}
          port: 22
          script: |
            security -v unlock-keychain -p "${{ secrets.ssh_password }}" ~/Library/Keychains/login.keychain-db

            export PATH=$PATH:/usr/bin:/usr/local/bin:/opt/homebrew/bin:/usr/local/opt/helm/bin

            cd Projects/${{ inputs.app_name }}
            
            git stash
            git fetch
            git reset origin/main --hard

            docker build -t ${{ inputs.app_name }}:${{ github.sha }} .
            docker tag ${{ inputs.app_name }}:${{ github.sha }} localhost:3010/${{ inputs.app_name }}:latest
            docker push localhost:3010/${{ inputs.app_name }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: marcusabukari.nl
          username: marcusabukari
          password: ${{ secrets.ssh_password }}
          port: 22
          script: |
            export PATH=$PATH:/usr/bin:/usr/local/bin:/opt/homebrew/bin:/usr/local/opt/helm/bin
            cd Projects/k8s
            # Doesnt work with latest tag
            # helm upgrade --install homelab .
            kubectl rollout restart deployment ${{ inputs.app_name }}

  notify:
    needs: [build, deploy]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Slack Notification - Success
        if: ${{ needs.build.result == 'success' && needs.deploy.result == 'success' }}
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "✅ *Deploy successful* for *${{ inputs.app_name }}* on `${{ github.ref_name }}` by `${{ github.actor }}`.",
              "attachments": [
                {
                  "color": "good",
                  "footer": "GitHub Actions • ${{ github.workflow }}",
                  "ts": "$(date +%s)"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}

      - name: Slack Notification - Failure
        if: ${{ needs.build.result != 'success' || needs.deploy.result != 'success' }}
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "❌ *Deploy failed* for *${{ inputs.app_name }}* on `${{ github.ref_name }}` by `${{ github.actor }}`.",
              "attachments": [
                {
                  "color": "danger",
                  "footer": "GitHub Actions • ${{ github.workflow }}",
                  "ts": "$(date +%s)"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
