name: Deploy Template

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      ssh_password:
        required: true
      slack_webhook_url:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ${{ inputs.app_name }}
        id: deploy_step
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: marcusabukari.nl
          username: marcusabukari
          password: ${{ secrets.ssh_password }}
          port: 22
          script: |
            security -v unlock-keychain -p "${{ secrets.ssh_password }}" ~/Library/Keychains/login.keychain-db

            export PATH=$PATH:/usr/bin:/usr/local/bin:/opt/homebrew/bin:/usr/local/opt/helm/bin

            cd Projects/${{ inputs.app_name }}

            git stash
            git fetch
            git reset origin/main --hard
            
            docker build -t ${{ inputs.app_name }}:latest .
            docker tag ${{ inputs.app_name }}:latest localhost:3010/${{ inputs.app_name }}:latest                                      
            docker push localhost:3010/${{ inputs.app_name }}:latest
            
            cd ../k8s
            helm upgrade --install homelab .

      - name: Slack Notification - Success
        if: success()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "✅ *Deploy successful* for *${{ inputs.app_name }}* on `${{ github.ref_name }}` by `${{ github.actor }}`.",
              "attachments": [
                {
                  "color": "good",
                  "footer": "GitHub Actions • ${{ github.workflow }}",
                  "ts": "$(date +%s)"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}

      - name: Slack Notification - Failure
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "❌ *Deploy failed* for *${{ inputs.app_name }}* on `${{ github.ref_name }}` by `${{ github.actor }}`.",
              "attachments": [
                {
                  "color": "danger",
                  "footer": "GitHub Actions • ${{ github.workflow }}",
                  "ts": "$(date +%s)"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
